# _config.yml
title: "Rasheed Ali Saadik Ali's Cybersecurity Portfolio"
description: > 
  A professional cybersecurity portfolio showcasing skills, projects, and learning journey.
theme: jekyll-theme-hacker
